batsmen = {
    "Sir Don Bradman": "Australia",
    "Sachin Tendulkar": "India",
    "Sir Vivian Richards": "West Indies",
    "Brian Lara": "West Indies",
    "Ricky Ponting": "Australia",
    "Jacques Kallis": "South Africa",
    "Sunil Gavaskar": "India",
    "Sir Garfield Sobers": "West Indies",
    "Rahul Dravid": "India",
    "Kumar Sangakkara": "Sri Lanka",
    "Steve Waugh": "Australia",
    "Mahela Jayawardene": "Sri Lanka",
    "Sir Jack Hobbs": "England",
    "Wally Hammond": "England",
    "Allan Border": "Australia",
    "Javed Miandad": "Pakistan",
    "Greg Chappell": "Australia",
    "Alastair Cook": "England",
    "Virender Sehwag": "India",
    "David Gower": "England",
    "Clive Lloyd": "West Indies",
    "Herbert Sutcliffe": "England",
    "Ken Barrington": "England",
    "Hanif Mohammad": "Pakistan",
    "Graeme Smith": "South Africa",
    "Shivnarine Chanderpaul": "West Indies",
    "Steve Smith": "Australia",
    "Martin Crowe": "New Zealand",
    "Michael Clarke": "Australia",
    "Saeed Anwar": "Pakistan",
    "Justin Langer": "Australia",
    "Kane Williamson": "New Zealand",
    "Joe Root": "England",
    "Younis Khan": "Pakistan",
    "Kevin Pietersen": "England",
    "Aravinda de Silva": "Sri Lanka",
    "Andy Flower": "Zimbabwe",
    "Mohammad Yousuf": "Pakistan",
    "Ross Taylor": "New Zealand",
    "AB de Villiers": "South Africa",
    "Adam Gilchrist": "Australia",
    "Gordon Greenidge": "West Indies",
    "Inzamam-ul-Haq": "Pakistan",
    "Sir Len Hutton": "England",
    "Allan Border": "Australia",
    "Javed Miandad": "Pakistan",
    "Kumar Sangakkara": "Sri Lanka",
    "Steve Waugh": "Australia",
    "Mahela Jayawardene": "Sri Lanka"
}

bowlers = {
    "Shane Warne": "Australia",
    "Muttiah Muralitharan": "Sri Lanka",
    "Wasim Akram": "Pakistan",
    "Glenn McGrath": "Australia",
    "Curtly Ambrose": "West Indies",
    "Malcolm Marshall": "West Indies",
    "Richard Hadlee": "New Zealand",
    "Dennis Lillee": "Australia",
    "Imran Khan": "Pakistan",
    "Waqar Younis": "Pakistan",
    "Dale Steyn": "South Africa",
    "Anil Kumble": "India",
    "James Anderson": "England",
    "Courtney Walsh": "West Indies",
    "Kapil Dev": "India",
    "Joel Garner": "West Indies",
    "Michael Holding": "West Indies",
    "Shaun Pollock": "South Africa",
    "Fred Trueman": "England",
    "Allan Donald": "South Africa",
    "Bishan Singh Bedi": "India",
    "Clarrie Grimmett": "Australia",
    "Sydney Barnes": "England",
    "Ray Lindwall": "Australia",
    "Bill O'Reilly": "Australia",
    "Lance Gibbs": "West Indies",
    "Saqlain Mushtaq": "Pakistan",
    "Harbhajan Singh": "India",
    "Stuart Broad": "England",
    "Mitchell Johnson": "Australia",
    "Chaminda Vaas": "Sri Lanka",
    "Zaheer Khan": "India",
    "Brett Lee": "Australia",
    "Andy Roberts": "West Indies",
    "Ian Botham": "England",
    "Bob Willis": "England",
    "Richard Hadlee": "New Zealand",
    "Shoaib Akhtar": "Pakistan",
    "Lasith Malinga": "Sri Lanka",
    "Makhaya Ntini": "South Africa",
    "Derek Underwood": "England",
    "Graeme Swann": "England",
    "Nathan Lyon": "Australia",
    "Rangana Herath": "Sri Lanka",
    "Daniel Vettori": "New Zealand",
    "Shakib Al Hasan": "Bangladesh",
    "Ravichandran Ashwin": "India",
    "Pat Cummins": "Australia",
    "Kagiso Rabada": "South Africa"
}
