quiz_data = {
    "Al-Khazneh": "Petra",
    "Angkor Wat": "Siem Reap",
    "Arc de Triomphe": "Paris",
    "Big Ben": "London",
    "Brandenburg Gate": "Berlin",
    "Buckingham Palace": "London",
    "Burj Khalifa": "Dubai",
    "Christ the Redeemer": "Rio de Janeiro",
    "Colosseum": "Rome",
    "Eiffel Tower": "Paris",
    "Empire State Building": "New York",
    "Forbidden City": "Beijing",
    "Golden Gate Bridge": "San Francisco",
    "Guggenheim Museum": "New York",
    "Hagia Sophia": "Istanbul",
    "Hollywood Sign": "Los Angeles",
    "Kremlin": "Moscow",
    "Leaning Tower of Pisa": "Pisa",
    "Louvre Museum": "Paris",
    "Mount Rushmore": "Keystone",
    "Notre-Dame Cathedral": "Paris",
    "Palace of Westminster": "London",
    "Pantheon": "Rome",
    "Petronas Towers": "Kuala Lumpur",
    "Pyramid of El Castillo": "Chichen Itza",
    "Pyramids of Giza": "Cairo",
    "Red Square": "Moscow",
    "Sistine Chapel": "Vatican City",
    "St. Basil's Cathedral": "Moscow",
    "St. Peter's Basilica": "Vatican City",
    "Statue of Liberty": "New York",
    "Stonehenge": "Wiltshire",
    "Sydney Opera House": "Sydney",
    "Taj Mahal": "Agra",
    "The Acropolis": "Athens",
    "The Alhambra": "Granada",
    "The Colosseum": "Rome",
    "Times Square": "New York",
}

# Sort the dictionary by keys
sorted_quiz_data = {k: v for k, v in sorted(quiz_data.items())}

print(sorted_quiz_data)
